import React, { useEffect, useState, useRef } from 'react';
import { MenuItem, Order, OrderStatus, Shop, User, CartItem } from '../types';
import { StorageService } from '../services/storage';
import { Button, Card, StatusBadge, Toast } from './ui';
import { ShoppingCart, Store, Plus, Minus, Bell, Pencil } from 'lucide-react';

interface WorkerDashboardProps {
  user: User;
}

export const WorkerDashboard: React.FC<WorkerDashboardProps> = ({ user }) => {
  const [activeTab, setActiveTab] = useState<'menu' | 'history'>('menu');
  const [shops, setShops] = useState<Shop[]>([]);
  const [menus, setMenus] = useState<MenuItem[]>([]);
  const [cart, setCart] = useState<CartItem[]>([]);
  const [myOrders, setMyOrders] = useState<Order[]>([]);
  const [selectedShopId, setSelectedShopId] = useState<string | null>(null);
  const [toast, setToast] = useState<{message: string, type?: 'info'|'success'} | null>(null);

  // Refs for tracking changes to trigger notifications
  const prevOrdersRef = useRef<Order[]>([]);
  const isFirstLoad = useRef(true);

  useEffect(() => {
    if (Notification.permission === 'default') {
      Notification.requestPermission();
    }
    
    // Subscribe to Firestore updates
    const unsubscribeShops = StorageService.subscribeToShops(setShops);
    const unsubscribeMenus = StorageService.subscribeToMenus(setMenus);
    const unsubscribeOrders = StorageService.subscribeToOrders((allOrders) => {
      // Filter client-side for simplicity, or could use query in service
      const userOrders = allOrders.filter(o => o.workerId === user.id).sort((a, b) => b.timestamp - a.timestamp);
      setMyOrders(userOrders);
    });

    return () => {
      unsubscribeShops();
      unsubscribeMenus();
      unsubscribeOrders();
    };
  }, [user.id]);

  // Effect to detect status changes and trigger notifications
  useEffect(() => {
    if (isFirstLoad.current) {
      if (myOrders.length > 0) {
        prevOrdersRef.current = myOrders;
        isFirstLoad.current = false;
      }
      return;
    }

    myOrders.forEach(order => {
      const prevOrder = prevOrdersRef.current.find(p => p.id === order.id);
      if (prevOrder && prevOrder.status !== order.status) {
        // Prepare message
        const msg = `Status pesanan #${order.id.slice(0, 4)}... berubah menjadi: ${order.status}`;
        
        // Show In-app Toast
        setToast({ message: msg, type: 'success' });
        
        // Show Browser Notification if allowed
        if (Notification.permission === 'granted') {
          new Notification('Update Pesanan KantinKantor', {
            body: msg,
            icon: '/icon.png' // Icon placeholder
          });
        }
      }
    });

    prevOrdersRef.current = myOrders;
  }, [myOrders]);

  const addToCart = (menu: MenuItem) => {
    setCart(prev => {
      const existing = prev.find(item => item.menuId === menu.id);
      if (existing) {
        return prev.map(item => item.menuId === menu.id ? { ...item, quantity: item.quantity + 1 } : item);
      }
      return [...prev, { ...menu, menuId: menu.id, quantity: 1, notes: '' }];
    });
  };

  const updateQuantity = (menuId: string, delta: number) => {
    setCart(prev => prev.map(item => {
      if (item.menuId === menuId) {
        return { ...item, quantity: Math.max(0, item.quantity + delta) };
      }
      return item;
    }).filter(item => item.quantity > 0));
  };

  const updateCartNote = (menuId: string, note: string) => {
    setCart(prev => prev.map(item => {
      if (item.menuId === menuId) {
        return { ...item, notes: note };
      }
      return item;
    }));
  };

  const placeOrder = async () => {
    if (cart.length === 0) return;

    const totalAmount = cart.reduce((sum, item) => sum + (item.price * item.quantity), 0);
    // Note: ID will be auto-generated by Firestore if we pass it as such, but here we set initial status
    const newOrder: Order = {
      // id will be ignored/overwritten by db logic or we can let Firestore generate
      id: '', 
      workerId: user.id,
      workerName: user.name,
      items: cart,
      totalAmount,
      status: OrderStatus.PROSES,
      timestamp: Date.now(),
    };

    await StorageService.saveOrder(newOrder);
    setCart([]);
    setActiveTab('history');
    setToast({ message: 'Pesanan berhasil dibuat!', type: 'success' });
  };

  const filteredMenus = selectedShopId 
    ? menus.filter(m => m.shopId === selectedShopId) 
    : menus;

  const cartTotal = cart.reduce((sum, item) => sum + (item.price * item.quantity), 0);

  return (
    <div className="max-w-4xl mx-auto p-4 pb-24">
      {toast && <Toast message={toast.message} type={toast.type} onClose={() => setToast(null)} />}
      
      <div className="flex justify-between items-center mb-6">
        <div>
          <h2 className="text-2xl font-bold text-gray-800">Halo, {user.name}</h2>
          <p className="text-gray-500">Mau makan apa hari ini?</p>
        </div>
        <div className="flex bg-white p-1 rounded-lg border shadow-sm">
          <button 
            onClick={() => setActiveTab('menu')}
            className={`px-4 py-2 rounded-md text-sm font-medium transition-colors ${activeTab === 'menu' ? 'bg-blue-50 text-blue-600' : 'text-gray-600 hover:bg-gray-50'}`}
          >
            Menu
          </button>
          <button 
            onClick={() => setActiveTab('history')}
            className={`px-4 py-2 rounded-md text-sm font-medium transition-colors ${activeTab === 'history' ? 'bg-blue-50 text-blue-600' : 'text-gray-600 hover:bg-gray-50'}`}
          >
            Riwayat
          </button>
        </div>
      </div>

      {activeTab === 'menu' && (
        <>
          {/* Shop Filter */}
          <div className="flex overflow-x-auto gap-2 mb-6 pb-2 hide-scrollbar">
            <button 
              onClick={() => setSelectedShopId(null)}
              className={`flex-shrink-0 px-4 py-2 rounded-full text-sm font-medium border ${!selectedShopId ? 'bg-gray-800 text-white border-gray-800' : 'bg-white text-gray-600 border-gray-200'}`}
            >
              Semua
            </button>
            {shops.map(shop => (
              <button
                key={shop.id}
                onClick={() => setSelectedShopId(shop.id)}
                className={`flex-shrink-0 px-4 py-2 rounded-full text-sm font-medium border ${selectedShopId === shop.id ? 'bg-gray-800 text-white border-gray-800' : 'bg-white text-gray-600 border-gray-200'}`}
              >
                {shop.name}
              </button>
            ))}
          </div>

          {/* Menu List */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mb-20">
            {filteredMenus.map(menu => {
              const shopName = shops.find(s => s.id === menu.shopId)?.name || 'Unknown Shop';
              return (
                <Card key={menu.id} className="hover:shadow-md transition-shadow flex flex-col h-full">
                  <div className="h-32 bg-gray-200 mb-3 rounded-lg overflow-hidden">
                    <img 
                      src={`https://picsum.photos/seed/${menu.id}/400/300`} 
                      alt={menu.name}
                      className="w-full h-full object-cover"
                    />
                  </div>
                  <div className="flex-1">
                    <div className="flex justify-between items-start mb-1">
                      <h3 className="font-semibold text-gray-900 line-clamp-1">{menu.name}</h3>
                      <span className="font-bold text-blue-600 text-sm">Rp{menu.price.toLocaleString()}</span>
                    </div>
                    <p className="text-xs text-gray-500 mb-4 flex items-center gap-1">
                      <Store size={12} /> {shopName}
                    </p>
                  </div>
                  <Button onClick={() => addToCart(menu)} className="w-full text-sm py-1.5 mt-auto">
                    + Tambah
                  </Button>
                </Card>
              );
            })}
          </div>

          {/* Sticky Cart Button */}
          {cart.length > 0 && (
            <div className="fixed bottom-4 left-4 right-4 md:left-auto md:right-8 md:w-96">
              <div className="bg-gray-900 text-white rounded-xl shadow-xl p-4">
                <div className="flex justify-between items-center mb-4 border-b border-gray-700 pb-2">
                  <span className="font-semibold flex items-center gap-2">
                    <ShoppingCart size={18} /> Keranjang ({cart.length})
                  </span>
                  <button onClick={() => setCart([])} className="text-gray-400 hover:text-white text-xs">Kosongkan</button>
                </div>
                <div className="max-h-60 overflow-y-auto mb-3 space-y-3 pr-1">
                  {cart.map(item => (
                    <div key={item.menuId} className="flex flex-col gap-1 border-b border-gray-800 pb-2 last:border-0">
                      <div className="flex justify-between items-start text-sm">
                        <div className="flex-1 truncate pr-2 font-medium">{item.name}</div>
                        <div className="flex items-center gap-3">
                          <button onClick={() => updateQuantity(item.menuId, -1)} className="p-1 hover:bg-gray-700 rounded"><Minus size={14}/></button>
                          <span>{item.quantity}</span>
                          <button onClick={() => updateQuantity(item.menuId, 1)} className="p-1 hover:bg-gray-700 rounded"><Plus size={14}/></button>
                        </div>
                        <div className="w-20 text-right font-mono text-gray-300">{(item.price * item.quantity).toLocaleString()}</div>
                      </div>
                      <input 
                        type="text"
                        placeholder="Catatan: pedas, tanpa bawang..."
                        className="text-xs bg-gray-800 text-gray-300 px-2 py-1 rounded border border-gray-700 focus:border-blue-500 focus:outline-none w-full"
                        value={item.notes || ''}
                        onChange={(e) => updateCartNote(item.menuId, e.target.value)}
                      />
                    </div>
                  ))}
                </div>
                <div className="flex justify-between items-center pt-2 border-t border-gray-700">
                  <div>
                    <div className="text-xs text-gray-400">Total</div>
                    <div className="font-bold text-lg">Rp{cartTotal.toLocaleString()}</div>
                  </div>
                  <Button onClick={placeOrder} className="bg-blue-500 hover:bg-blue-400 text-white">
                    Pesan Sekarang
                  </Button>
                </div>
              </div>
            </div>
          )}
        </>
      )}

      {activeTab === 'history' && (
        <div className="space-y-4">
           <div className="bg-blue-50 text-blue-800 p-4 rounded-lg flex items-start gap-3">
             <Bell className="mt-1 flex-shrink-0" size={20} />
             <div>
               <p className="font-medium text-sm">Notifikasi Real-time Aktif</p>
               <p className="text-xs opacity-80">Anda akan menerima notifikasi saat status pesanan berubah.</p>
             </div>
           </div>

          {myOrders.length === 0 ? (
            <div className="text-center py-10 text-gray-500">Belum ada pesanan. Yuk pesan makan!</div>
          ) : (
            myOrders.map(order => (
              <Card key={order.id} className={`border-l-4 ${order.status === OrderStatus.FINISH ? 'border-l-green-500 opacity-90' : 'border-l-blue-500'}`}>
                <div className="flex justify-between items-start mb-3">
                  <div>
                    <div className="text-xs text-gray-400 mb-1">{new Date(order.timestamp).toLocaleString('id-ID')}</div>
                    <h3 className="font-semibold text-gray-900">Order #{order.id.slice(0, 6)}...</h3>
                  </div>
                  <StatusBadge status={order.status} />
                </div>
                <div className="space-y-2 mb-3">
                  {order.items.map((item, idx) => (
                    <div key={idx} className="text-sm text-gray-700">
                      <div className="flex justify-between">
                        <span>{item.quantity}x {item.name}</span>
                        <span>Rp{(item.price * item.quantity).toLocaleString()}</span>
                      </div>
                      {item.notes && (
                        <div className="text-xs text-gray-500 italic ml-4">- Catatan: {item.notes}</div>
                      )}
                    </div>
                  ))}
                </div>
                <div className="flex justify-between items-center pt-3 border-t border-gray-100">
                  <span className="text-sm font-semibold text-gray-900">Total Bayar</span>
                  <span className="text-lg font-bold text-blue-600">Rp{order.totalAmount.toLocaleString()}</span>
                </div>
              </Card>
            ))
          )}
        </div>
      )}
    </div>
  );
};